# -*- coding: utf-8 -*-
import os

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-in-production")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
PERMANENT_SESSION_LIFETIME = 86400
SHIFT_DURATION_HOURS = 12
SHIFT_DURATION_SECONDS = None
LOW_STOCK_THRESHOLD = 5
MONEY_DECIMALS = 2
PERCENT_DECIMALS = 1
